mm_ros_control:
  type        : "mm_ros_control/mmRosControl"
  publish_rate: 50


  arm_joint_names:
    - armjoint_1
    - armjoint_2
    - armjoint_3
    - armjoint_4
    - armjoint_5
    - armjoint_6

  gripper_joint_names:
    - left_outer_knuckle_joint

    
  qp_params:
    K_theta: 0.05
    mt: 0
    Y: 0.1
    KpSteer: 1.5
  
  the_odom_topic:  "odometry_controller/odom"
  